name: check push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: use Node
          uses: actions/setup-node@v2
          with:
            node-version: 12.x
      - name: install and gen
          run: |
            npm install
            npm run docs
      - name: gendocs
          run: |
            cd docs
            git init
            git add .
            git commit
            git remote add origin https://${{ secrets.CI_PAGE_PUSH_USERNAME }}:{{ secrets.CI_PUSH_PAGE_TOKEN }}@github.com/sea-design/sea-design.github.io.git
            git push -f origin main

